### ISSUE TITLE
Show IP DDoS attacks for VPS

### ISSUE THREAD

**Issue by SystemZ** [lvlup-pro/spawn-frontend-material#136]
Let's use new endpoint `GET https://api.lvlup.pro/v3/vps/:id/ip/:ip/ddos`

https://api.lvlup.pro/docs/#api-Vps-VpsIpDdos

This list can be long so we need to use pagination for this.
For now there is info about start and end of attack, in the future there should be last updated timestamp too.

**Comment by SystemZ** [comment]
Ok so list page is implemented in 249531472dce7b032ff575b5084b76457f23c217 but I don't know where to put link to it on VPS page.
@Libter  Any ideas?

**Comment by Libter** [comment]
Maybe "ATTACKS" button floating right on the bottom of the card?

**Comment by SystemZ** [comment]
I just added text like date creation in beta 9, let's hear users opinion :)

**Comment by Libter** [comment]
Unfortunately that text doesn't support multiple IPs, fixed in #144.

**Comment by SystemZ** [comment]
It works for now so I'm closing this issue.
