### ISSUE TITLE
List of DDoS attacks

### ISSUE THREAD

**Issue by kacperduras** [lvlup-pro/spawn-frontend-material#145]
By checking the list of DDoS attacks on my VPS I noticed that I had an attack March 19, 2016 year. The problem is that the service I have purchased from 2 months :>

**Comment by Libter** [comment]
Maybe there were some attacks in the past when IP was bound to another VPS?

**Comment by SystemZ** [comment]
True, in current version of backend, behaviour is to show all attacks to this IP.
Should be fixed tommorow, I wanted to push this function to public ASAP and ignored this because I think it's not security related.

**Comment by SystemZ** [comment]
Fixed along with the release of 3.0.0-beta.10
