### ISSUE TITLE
Fix forms and sidebar for vuetify 0.9.2

### ISSUE THREAD

**Issue by SystemZ** [lvlup-pro/spawn-frontend-material#156]
Next version of vuetify have some huge improvments, for example vertical stepper which we can use for order page easily
https://vuetifyjs.com/components/steppers

Neat element for notifications:
https://vuetifyjs.com/components/snackbars

Input text, finally for submiting ticket messages! No more textarea hacks
https://vuetifyjs.com/components/text-fields

Please send PR to this branch to don't disturb current stable builds
https://github.com/lvlup-pro/spawn-frontend-material/tree/vuetify-0.9.2

**Comment by Libter** [comment]
Probably resolved since d7d367b.

**Comment by SystemZ** [comment]
True :)
