### ISSUE TITLE
Service list API

### ISSUE THREAD

**Issue by kacperduras** [lvlup-pro/spawn-frontend-material#172]
I have a suggestion, already referring to the API. Namely, when we make a query from [here](https://api.lvlup.pro/docs/#api-Service-ServiceList), there would be an extra `type` field, and there would be a type of service. This is useful for interpreting data through the program, because you do not need to perform separate queries for domains, VPSs, and other services. For unification, this could be added to any service (even if we downloaded them separately).

**Comment by kacperduras** [comment]
@SystemZ any answer? labels? nothing? D:

**Comment by SystemZ** [comment]
Current service list endpoint is only a draft and may change.
I'll look into it.
