### ISSUE TITLE
Can't login while testing on localhost

### ISSUE THREAD

**Issue by Libter** [lvlup-pro/spawn-frontend-material#18]
`XMLHttpRequest cannot load https://demoapi.lvlup.pro/v3/auth/login. Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'https://demomy.lvlup.pro' that is not equal to the supplied origin. Origin 'http://localhost:8080' is therefore not allowed access.`

Please set `Access-Control-Allow-Origin` to `*`.

**Comment by SystemZ** [comment]
Sandbox env demoapi.lvlup.pro now has `Access-Control-Allow-Origin` set to `*`
