### ISSUE TITLE
"More" button should be lower

### ISSUE THREAD

**Issue by SystemZ** [lvlup-pro/spawn-frontend-material#25]
![32f11076005eebb09f825f379bddcd15ecadab2f_1_690x69](https://cloud.githubusercontent.com/assets/1836094/22865822/bea36d9a-f16b-11e6-8976-f302f16e0e58.PNG)

**Comment by SystemZ** [comment]
Temporary disabling this menu in #30

**Comment by SystemZ** [comment]
Anyway, what we should put in this right side of toolbar, any ideas? If only logout then we can just move it to sidebar.

Maybe some kind of notifications with bell icon?

**Comment by Libter** [comment]
I think that currently we don't need anything in right side of toolbar. Notification bell icon may be added in the future after v3.0.0.

**Comment by SystemZ** [comment]
True, let's close that issue.
