### ISSUE TITLE
Checking boxes on pagination - what actions should be available?

### ISSUE THREAD

**Issue by SystemZ** [lvlup-pro/spawn-frontend-material#9]
We can check boxes on tables, but for what we can use it?

**Comment by Libter** [comment]
I can't imagine any uses for payments and tickets. Checkboxes make some sense only in services table: mass renewal, unifying renewal dates, etc.

**Comment by SystemZ** [comment]
Maybe ticket and payment archiving? I use it a lot in in Gmail.

**Comment by SystemZ** [comment]
Currently I see it usable only on UDP whitelist rules list so I'm closing it.
