### ISSUE TITLE
Invalid VPS status on services page

### ISSUE THREAD

**Issue by Libter** [lvlup-pro/spawn-frontend-material#95]
Services.vue: 
![image](https://cloud.githubusercontent.com/assets/5753763/23357333/a7dad3b4-fcdd-11e6-832f-e39cc633fb4c.png)

VPS.vue: 
![image](https://cloud.githubusercontent.com/assets/5753763/23357323/95dfecee-fcdd-11e6-87b4-a833cd992443.png)

store.state.services.items[n]:
![image](https://cloud.githubusercontent.com/assets/5753763/23357275/5f9b4ade-fcdd-11e6-9d91-753fe0c39b51.png)

store.state.vps:
![image](https://cloud.githubusercontent.com/assets/5753763/23357305/8490db24-fcdd-11e6-8b45-05ff4a030c95.png)

**Comment by SystemZ** [comment]
`running` shoud not be there in the first place `store.state.services.items[n]`
Now it's removed from backend.
Current realtime status is provided only via GET `/v3/vps/:id`.

Instead of `running` in vps list, let's just use `active` for telling user if server is payed.
